apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "aac-org.fullname" . }}-env
  namespace: {{ template "aac-org.namespace" . }}
  labels:
  {{- include "aac-org.labels" . | nindent 4 }}
data:
  APPLICATION_URL: {{ .Values.application_url }}
  OAUTH2_ISSUER_URI: {{ .Values.aac.issuer_uri}}
  AAC_URI: {{ .Values.aac.uri}}
  LOG_LEVEL: {{ .Values.loglevel }}
  JAVA_OPTS: {{ .Values.javaOpts | default "-XX:MaxRAMFraction=2" }}
