apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "aac-org.fullname" . }}-env
  namespace: {{ template "aac-org.namespace" . }}
  labels:
  {{- include "aac-org.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.serverPort | quote }}
  OMC_SERVER_SERVLET_SESSION_COOKIE_NAME: {{ .Values.sessionCookieName }}
  MANAGEMENT_PORT: {{ .Values.managementPort | quote }}
  APPLICATION_URL: {{ .Values.applicationUrl }}
  LOG_LEVEL: {{ .Values.logLevel }}
  JAVA_OPTS: {{ .Values.javaOpts | default "-XX:MaxRAMFraction=2" }}
  OAUTH2_ISSUER_URI: {{ .Values.aac.issuerUri }}
  AAC_URI: {{ .Values.aac.uri }}
