nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
replicasCount: 1

auth:
  enabled: false
  provider: ""
  authorizationUrl: ""
  clientId: ""
  scopes: profile.basicprofile.me user.roles.me
  userProfileEndpoint: ""
  tokenValidityEndpoint: ""
  userRolesEndpoint: ""
  tokenInfoEndpoint: ""
  tokenRolesEndpoint: ""
  apikeyCheckEndpoint: ""
  parentSpace: ""

site:
  image:
    repository: smartcommunitylab/cyclotron-site
    tag: 5985d90
    pullPolicy: IfNotPresent

  labels: {}

  confs:
    existingSecret: ""
    filePath: ""
    fileName: ""

  resources: {}
    # limits:
    #   cpu: "1000m"
    #   memory: "512Mi"
    # requests:
    #   cpu: "250m"
    #   memory: "256Mi"

  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 40
    periodSeconds: 5
    successThreshold: 2

  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 30
    periodSeconds: 10

  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  service:
    name: http
    type: ClusterIP
    port: 80
    labels: {}

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

    annotations: {}

    auth:
      enabled: false
      provider: ""
      authorizationUrl: ""
      clientId: ""
      scopes: profile.basicprofile.me user.roles.me
      userProfileEndpoint: ""
      tokenValidityEndpoint: ""

svc:
  url: ""
  image:
    repository: smartcommunitylab/cyclotron-svc
    tag: 5985d90
    pullPolicy: IfNotPresent

  labels: {}

  confs:
    existingSecret: ""
    filePath: ""
    fileName: ""

  mongo:
    user:
    password:
    url:
    dbName:

  resources: {}
    # limits:
    #   cpu: "1000m"
    #   memory: "512Mi"
    # requests:
    #   cpu: "250m"
    #   memory: "256Mi"

  readinessProbe:
    httpGet:
      path: /
      port: 8077
    initialDelaySeconds: 40
    periodSeconds: 5
    successThreshold: 2

  livenessProbe:
    httpGet:
      path: /
      port: 8077
    initialDelaySeconds: 30
    periodSeconds: 10

  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  service:
    name: http
    type: ClusterIP
    port: 8077
    labels: {}

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []

    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

    annotations: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
