bootstrap:
  clients:
    - name: WSO2 API Manager
      id: uom9BViJ-c3pQ-Jb0E-xm1K-cV9U-rdpIOui4wQGn
      secret: Jc1jc7yt-2HiH-05X3-53LO-5yDm-tK8WG1lDIU2t
      developer: admin
      grantTypes:
      - implicit
      - refresh_token
      - password
      - client_credentials
      - authorization_code
      redirectUris:
      - https://api.kube-test.smartcommunitylab.it/
      rolePrefixes:
      - components/apimanager/
      scopes:
      - openid
      - profile
      - profile.basicprofile.me
      - profile.basicprofile.all
      - apimanagement
      - profile.accountprofile.me
      - email
      - user.roles.me
      - "apim:api_view"
      - "apim:api_create"
      - "apim:api_publish"
      trusted: true

    - name: dss
      id: BBoAt563-1pNF-5OvS-2caE-W4rK-zG8Vbro5n2Km
      secret: f0rjMnK5-NeF3-OV8d-g7jA-QiB0-Elm8AO0UzDXX
      developer: admin
      grantTypes:
      - implicit
      - client_credentials
      - authorization_code
      redirectUris:
      - https://dss.kube-test.smartcommunitylab.it/
      rolePrefixes:
      - components/dss/
      scopes:
      - openid
      - profile
      - profile.basicprofile.me
      - user.roles.me
      trusted: true

    - name: nifi
      id: 6wLlM5LH-mg3R-Pr6E-mG4W-8YDM-64203Hf007dY
      secret: T6lpdUIK-w2Ke-Z4X8-9tAz-Pk81-zMMpd0HZFKCe
      afterApprovalWebhook: http://nuclio-nodejs-nifi-connector.sys.svc.cluster.local:8080
      claimMappingFunction: LyoqCiAqIERFRklORSBZT1VSIE9XTiBDTEFJTSBNQVBQSU5HIEhFUkUKICogVE8gQkUgUFVUIElOIEFBQyBDT05GSUcgT0YgTklGSSBDTElFTlQgQVBQCioqLwpmdW5jdGlvbiBjbGFpbU1hcHBpbmcoY2xhaW1zKSB7CiAgICAvLyBleHRyYWN0IHJvbGVzCiAgICB2YXIgcGF0aCA9ICdjb21wb25lbnRzL25pZmkvJzsKICAgIGlmKGNsYWltcy5yb2xlcyAmJiBjbGFpbXMucm9sZXMgIT0gbnVsbCAmJiBjbGFpbXMucm9sZXMgIT0gdW5kZWZpbmVkKXsKICAgICAgICB2YXIgcm9sZXMgPSBjbGFpbXMucm9sZXMuZmlsdGVyKGZ1bmN0aW9uKHIpIHsKICAgICAgICAgICAgICAgIHJldHVybiByLmluZGV4T2YocGF0aCkgPT0gMDsKICAgICAgICAgICAgfSkKICAgICAgICAgICAgLm1hcChmdW5jdGlvbihyKSB7CiAgICAgICAgICAgICAgICB2YXIgc3Vicm9sZSA9IHIuc3Vic3RyaW5nKHBhdGgubGVuZ3RoKTsKICAgICAgICAgICAgICAgIHZhciBhID0gc3Vicm9sZS5zcGxpdCgnOicpOwogICAgICAgICAgICAgICAgcmV0dXJuIHsKICAgICAgICAgICAgICAgICAgICBvcmc6IGFbMF0ucmVwbGFjZSgvXC8vZywgJ18nKS5yZXBsYWNlKC9cLi9nLCAnXycpLAogICAgICAgICAgICAgICAgICAgIHJvbGU6IGFbMV0KICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgfSkKICAgICAgICAgICAgLnJlZHVjZShmdW5jdGlvbihwcmV2LCBjdXJyKSB7IAogICAgCSAgICAvLyB0aGUgY2F0ZWdvcmllcyBvZiByb2xlcyBpbiBOaUZpCiAgICAgICAgICAgICAgICBpZihjdXJyLnJvbGUgPT09ICdST0xFX01BTkFHRVInKQogICAgICAgICAgICAgICAgICAgIHByZXZbY3Vyci5vcmddID0gJ1JPTEVfTUFOQUdFUic7CiAgICAgICAgICAgICAgICBpZighcHJldltjdXJyLm9yZ10pCiAgICAgICAgICAgICAgICAgICAgcHJldltjdXJyLm9yZ10gPSAnUk9MRV9NT05JVE9SJzsKICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgcmV0dXJuIHByZXY7CiAgICAgICAgICAgIH0sIHt9KTsKICAgICAgICBjbGFpbXNbJ25pZmkvcm9sZXMnXSA9IHJvbGVzOwogICAgfQogICAgcmV0dXJuIGNsYWltczsKfQ==
      developer: admin
      grantTypes:
      - client_credentials
      - authorization_code
      redirectUris:
      - https://nifi.kube-test.smartcommunitylab.it/
      rolePrefixes:
      - components/nifi/
      uniqueSpaces: [
      ]
      scopes:
      - openid
      - profile
      - email
      - user.roles.me
      trusted: true

    - name: cyclotron
      id: xaqkd7Tf-8dwN-p4iU-prh3-ga9r-qRiJSBKvoW1Q
      secret: TEz9bqTA-57HD-h3hY-mD3q-NM0V-Asm08fMvnio3
      developer: admin
      grantTypes:
      - implicit
      - refresh_token
      - client_credentials
      - authorization_code
      redirectUris:
      - https://cyclotron.kube-test.smartcommunitylab.it/
      rolePrefixes:
      - components/cyclotron/
      scopes:
      - openid
      - profile
      - profile.basicprofile.me
      - email
      - user.roles.me
      trusted: true

  users:
    - username: test
      password: test123
      roles:
    - username: grafana@kube.test.it
      password: grafana
      roles:
    - username: test1@kube.test.it
      password: yHWRZKNmsFMOFFlD0Kw0
      roles:
    - username: test2@kube.test.it
      password: eDkSxwOAAbY3OOAYPqmc
      roles:
    - username: test3@kube.test.it
      password: e2NA6NZVjKPPcZ8Ijz2J
      roles:
    - username: test4@kube.test.it
      password: e2NA6NZVjKPPcZ8Ijz2J
      roles:

  services:
    - serviceId: security.vault
      name: Vault Data Service
      description: Core service for managing secure resource access and data.
      scopes:
      - scope: vault.data.read
        name: Read Vault data
        description: Read Vault data programmatically
        claims: []
        roles: []
        authority: ROLE_CLIENT
        approvalRequired: false
      - scope: vault.data.read.me
        name: Read Current User Vault Data
        description: Read Vault data of the current user
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: true
      claims: []
    - serviceId: apim.rest
      name: API Manager REST APIs access
      description: Service for the scopes expected by API Manager to access its REST APIs.
      scopes:
      - scope: apim:api_view
        name: View APIs
        description: Find APIs and view details
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:api_create
        name: Create and edit APIs
        description: Create, edit and delete APIs
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:api_publish
        name: Change API status
        description: Publish, revoke, retire APIs
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:mediation_policy_view
        name: View mediation policies
        description: View mediation policies
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:mediation_policy_create
        name: Manage mediation policies
        description: Manage mediation policies
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:subscription_view
        name: View subscriptions
        description: View subscriptions
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:subscription_block
        name: Block and unblock subscriptions
        description: Block and unblock subscriptions
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:tier_view
        name: View throttling tiers
        description: View throttling tiers
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:tier_manage
        name: Manage throttling tiers
        description: Manage throttling tiers
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:api_workflow
        name: Update workflow status
        description: Update workflow status
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:subscribe
        name: View and manage subscriptions
        description: View and manage subscriptions
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:bl_view
        name: View blacklists
        description: View blacklists
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:bl_manage
        name: Manage blacklists
        description: Manage blacklists
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      claims: []
