bootstrap:
  clients:
    - name: WSO2 API Manager
      id: APIM_CLIENT_ID
      secret: APIM_CLIENT_SECRET
      developer: admin
      grantTypes:
      - implicit
      - refresh_token
      - password
      - client_credentials
      - authorization_code
      redirectUris:
      - https://api.platform.local
      scopes:
      - openid
      - profile
      - user.roles.me
      - "apim:api_view"
      - "apim:api_create"
      - "apim:api_publish"
      trusted: false

    - name: WSO2 Data Services Server
      id: DSS_CLIENT_ID
      secret: DSS_CLIENT_SECRET
      developer: admin
      grantTypes:
      - implicit
      - client_credentials
      - authorization_code
      redirectUris:
      - https://dss.platform.local
      scopes:
      - openid
      - profile
      - user.roles.me
      - profile.basicprofile.me
      - apikey.user.me
      - apikey.user.client
      trusted: false

    - name: Apache NiFi
      id: NIFI_CLIENT_ID
      secret: NIFI_CLIENT_SECRET
      developer: admin
      grantTypes:
      - implicit
      - client_credentials
      - authorization_code
      redirectUris:
      - https://nifi.platform.local/nifi-api/access/oidc/callback
      scopes:
      - openid
      - profile
      - email
      - user.roles.me
      trusted: false

    - name: Cyclotron
      id: CYCLOTRON_CLIENT_ID
      secret: CYCLOTRON_CLIENT_SECRET
      developer: admin
      grantTypes:
      - implicit
      - refresh_token
      - password
      - client_credentials
      - authorization_code
      redirectUris:
      - https://cyclotron.platform.local
      scopes:
      - openid
      - profile
      - user.roles.me
      trusted: false

  users:
    - username: test
      password: test123
      roles:
    - username: grafana@kube.test.it
      password: grafana
      roles:
    - username: test1@kube.test.it
      password: yHWRZKNmsFMOFFlD0Kw0
      roles:
    - username: test2@kube.test.it
      password: eDkSxwOAAbY3OOAYPqmc
      roles:
    - username: test3@kube.test.it
      password: e2NA6NZVjKPPcZ8Ijz2J
      roles:
    - username: test3@kube.test.it
      password: e2NA6NZVjKPPcZ8Ijz2J
      roles:

  services:
    - serviceId: security.vault
      name: Vault Data Service
      description: Core service for managing secure resource access and data.
      scopes:
      - scope: vault.data.read
        name: Read Vault data
        description: Read Vault data programmatically
        claims: []
        roles: []
        authority: ROLE_CLIENT
        approvalRequired: false
      - scope: vault.data.read.me
        name: Read Current User Vault Data
        description: Read Vault data of the current user
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: true
      claims: []
    - serviceId: apim.rest
      name: API Manager REST APIs access
      description: Service for the scopes expected by API Manager to access its REST APIs.
      scopes:
      - scope: apim:api_view
        name: View APIs
        description: Find APIs and view details
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:api_create
        name: Create and edit APIs
        description: Create, edit and delete APIs
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      - scope: apim:api_publish
        name: Change API status
        description: Publish, revoke, retire APIs
        claims: []
        roles: []
        authority: ROLE_USER
        approvalRequired: false
      claims: []