---
# Source: aac/templates/aac-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: aac
  namespace: global
  labels:
    helm.sh/chart: aac-0.1.8
    app.kubernetes.io/name: aac
    app.kubernetes.io/instance: aac
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: aac
    app.kubernetes.io/instance: aac
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
