apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gatekeeper.fullname" . }}-env
  namespace: {{ template "gatekeeper.namespace" . }}
  labels:
  {{- include "gatekeeper.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.options }}
    {{- if $value }}
{{ $key | upper | indent 2 }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
