apiVersion: v1
kind: Service
metadata:
  name: {{ template "gatekeeper.fullname" . }}
  namespace: {{ template "gatekeeper.namespace" . }}
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  selector:
    {{- include "gatekeeper.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
