version: "3.7"
services:
  am-analytics:
    image: smartcommunitylab/apim-analytics:auto
    ports:
      - "9091"
      - "9444"
      - "7712"
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9091"]
      interval: 10s
      timeout: 120s
      start_period: 120s
      retries: 10
    env_file:
      - apim-analytics.env
    volumes:
      - ./cert/am-analytics/am-analytics.jks:/home/wso2carbon/wso2-config-volume/resources/security/am-analytics.jks
      - ./cert/am-analytics/client-truststore.jks:/home/wso2carbon/wso2-config-volume/resources/security/client-truststore.jks
    networks:
      platform-net:
networks:
  platform-net:
    external: true
    name: platform-net
