version: "3.7"
services:
  mysql:
    image: mysql:5
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    command: --max-connections=1000
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init-script/apim_init.sql:/docker-entrypoint-initdb.d/apim_init.sql
      - ./db-init-script/aac_init.sql:/docker-entrypoint-initdb.d/aac_init.sql
      - ./db-init-script/dss_init.sql:/docker-entrypoint-initdb.d/dss_init.sql
    networks:
      platform-net: {}
  # mongo:
  #   image: mongo:3.6
  #   ports:
  #     - 27017
  #   environment:
  #     MONGO_INITDB_ROOT_PASSWORD: 'ac'
  #     MONGO_INITDB_ROOT_USERNAME: 'ac'
  #   volumes:
  #     - mongo_data:/data/db
  #   networks:
  #     platform-net: {}
  # postgres:
  #   image: postgres:10
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: 'ac'
  #     POSTGRES_PASSWORD: 'ac'
  #   command: ['-c', 'config_file=/etc/postgresql/postgresql.conf']
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #     - ./postgresql.conf:/etc/postgresql/postgresql.conf
  #     - /home/ffais/tmp/traffic_script:/script
  #   networks:
  #     platform-net: {}
volumes:
  mysql_data: {}
  # mongo_data: {}
  # postgres: {}
networks:
  platform-net:
    external: true
