version: "3.7"
services:
  dss-wso2:
    image:  smartcommunitylab/dss:auto_latest
    ports:
      - "9764:9763"
      - "9445:9443"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/oauth2-sso-acs/custom_login.jsp"]
      interval: 10s
      timeout: 120s
      start_period: 100s
      retries: 10
    env_file:
      - dss.env
    networks:
      platform-net:
# volumes:
#   server: {}
#   tenants: {}
#   #solr: {}
networks:
  platform-net:
    external: true
    name: platform-net
