version: "3.7"
services:
  dss-wso2:
    image: smartcommunitylab/dss:6cc9497
    ports:
      - "9764:9763"
      - "9445:9443"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/oauth2-sso-acs/custom_login.jsp"]
      interval: 10s
      timeout: 120s
      start_period: 100s
      retries: 10
    env_file:
      - dss.env
    volumes:
        - ./cert/dss.platform.local/dss.jks:/home/wso2carbon/wso2-config-volume/repository/resources/security/dss.jks
        - ./cert/dss.platform.local/client-truststore.jks:/home/wso2carbon/wso2-config-volume/repository/resources/security/client-truststore.jks
    networks:
      platform-net:
networks:
  platform-net:
    external: true
    name: platform-net
