version: "3.7"
services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./cert/platform-wildcard.pem:/etc/nginx/ssl/platform/platform-wildcard.pem"
      - "./cert/platform-wildcard.key:/etc/nginx/ssl/platform/platform-wildcard.key"
      - "./cert/dhparam.pem:/etc/nginx/ssl/platform/dhparam.pem"
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx-ssl.conf:/etc/nginx/nginx-ssl.conf"
    networks:
      platform-net:
networks:
  platform-net:
    external: true
    name: platform-net
