version: "3.7"
services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./cert/star.platform.local/star.platform.local.crt:/etc/nginx/ssl/platform/platform-wildcard.pem"
      - "./cert/star.platform.local/star.platform.local.key:/etc/nginx/ssl/platform/platform-wildcard.key"
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx-ssl.conf:/etc/nginx/nginx-ssl.conf"
    networks:
      platform-net:
        aliases:
          - aac.platform.local
networks:
  platform-net:
    external: true
    name: platform-net
