version: "3.7"
services:
  nifi:
    image: smartcommunitylab/nifi:latest #aac-org:t
    # image: nifi
    ports:
      - "8443:8443"
    env_file:
      nifi_param.env
    entrypoint: '/opt/nifi/scripts/start.sh'
    volumes:
      - "./cert/nifi.platform.local/nifi.platform.local:/opt/nifi/nifi-current/certs"
    networks:
      platform-net: {}
networks:
  platform-net:
    external: true
