apiVersion: v1
kind: Service
metadata:
  name: {{ template "nifi.fullname" . }}
  namespace: {{ template "nifi.namespace" . }}
  labels:
    {{- include "nifi.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  selector:
    {{- include "nifi.selectorLabels" . | nindent 4 }}
  ports:
    # ports that this service should serve on
    - name: http
      port: 8080
    #  targetPort: 8080
      protocol: "TCP"
    - name: https
      port: 8443
    #  targetPort: 8443
      protocol: "TCP"
    - name: remotesocket
      port: 10000
    #  targetPort: 10000
      protocol: "TCP"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nifi.fullname" . }}-simple
  namespace: {{ template "nifi.namespace" . }}
  labels:
    {{- include "nifi.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  selector:
    {{- include "nifi.selectorLabels" . | nindent 4 }}
  ports:
    # ports that this service should serve on
    - name: http
      port: 8080
    #  targetPort: 8080
      protocol: "TCP"
    - name: https
      port: 8443
    #  targetPort: 8443
      protocol: "TCP"
    - name: remotesocket
      port: 10000
    #  targetPort: 10000
      protocol: "TCP"
