{{- if (not .Values.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "aac.fullname" . }}-admin-creds
  namespace: {{ template "aac.namespace" . }}
  labels:
    {{- include "aac.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.admin.userName | default "admin" | b64enc | quote  }}
  {{- if .Values.admin.password }}
  password: {{ .Values.admin.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
{{- end}}
---
{{- if (not .Values.externalBootstrapFile.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "aac.fullname" . }}-bootstrap
  namespace: {{ template "aac.namespace" . }}
  labels:
    {{- include "aac.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ tpl (.Files.Get "confs/config.yaml") . | b64enc }}
{{ end }}
