apiVersion: v1
kind: Service
metadata:
  name: {{ template "aac.fullname" . }}
  namespace: {{ template "aac.namespace" . }}
  labels:
    {{- include "aac.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  selector:
    {{- include "aac.selectorLabels" . | nindent 4 }}
  ports:
  - name: {{ .Values.service.portName | default "http" }}
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
{{- if .Values.service.extraPorts }}
{{ toYaml .Values.service.extraPorts | indent 2 }}
{{- end }}
