{{- if .Values.randomClientIdSecret }}
{{- range $key, $val := .Values.defaultClientApplication }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ if eq $key "aacOrg" -}}
    aac-org-aac-creds
  {{- else if eq $key "apiManager" -}}
    api-manager-aac-creds
  {{- else if eq $key "resourceManager" -}}
    resource-manager-aac-creds
  {{- else -}}
    {{ $key }}-aac-creds
  {{- end }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  namespace: {{ template "aac.namespace" }}
  labels:
    {{- include "aac.labels" $ | nindent 4 }}
type: Opaque
data:
    {{- $clientId := $val | toString | regexFind "clientId:[a-zA-z0-9]{8}-[a-zA-z0-9]{4}-[a-zA-z0-9]{4}-[a-zA-z0-9]{4}-[a-zA-z0-9]{4}-[a-zA-z0-9]{12}" | trimPrefix "clientId:" }}
    {{- $clientSecret := $val | toString | regexFind "clientSecret:[a-zA-z0-9]{8}-[a-zA-z0-9]{4}-[a-zA-z0-9]{4}-[a-zA-z0-9]{4}-[a-zA-z0-9]{4}-[a-zA-z0-9]{12}" | trimPrefix "clientSecret:" }}
    username: {{ $clientId | b64enc | quote }}
    password: {{ $clientSecret | b64enc | quote }}
    {{- if eq $key "gatekeeper" }}
    encryptionkey: {{ randAlphaNum 32 | b64enc | quote }}
    {{- end }}
---
{{- end }}
{{- end }}
